before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      main: ./cmd/test-reporter/main.go
      binary: "test-reporter"
      env:
        - CGO_ENABLED=0
      ldflags:
        - -X main.Version={{.Version}}
        - -X main.Commit={{.ShortCommit}}
      hooks:
        post:
          - upx "{{ .Path }}"
      id: linux
      goos: [linux]
      goarch: [amd64, arm64]

  - <<: *build_defaults
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64]

snapshot:
  name_template: "SNAPSHOT-{{.ShortCommit}}"

archives:
  - id: default
    format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
  - id: snake_case # Also offer binaries with snake_case filenames to support the updated URLs implemented in response to the 2021-09-20 GitHub incident (https://twitter.com/BuildPulseApp/status/1440089498566623241)
    format: binary
    name_template: "test_reporter_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
