language: go

go:
  - 1.19.x

script:
  - sudo apt-get update -y
  - sudo apt-get install -y upx
  - ./script/build-snapshot
  - ./dist/linux_linux_amd64/test-reporter --version
  - mkdir -p fake-test-results-dir
  - touch fake-test-results-dir/report.xml
  - ./dist/linux_linux_amd64/test-reporter submit fake-test-results-dir --account-id 68192324 --repository-id 280914963
