version: 2.1

jobs:
  smoke-test:
    docker:
      - image: cimg/go:1.16

    steps:
      - checkout

      - run:
          name: Build executable binaries
          command: |
            sudo apt-get update -y
            sudo apt-get install -y upx
            ./script/build-snapshot

      - run:
          name: Output version
          command: ./dist/test_reporter_linux_amd64/test-reporter --version

      - run:
          name: Verify binary can successfully package up test results and upload them to BuildPulse
          command: |
            mkdir -p fake-test-results-dir
            touch fake-test-results-dir/report.xml
            ./dist/test_reporter_linux_amd64/test-reporter submit fake-test-results-dir --account-id 68192324 --repository-id 280914963

workflows:
  version: 2
  build-workflow:
    jobs:
      - smoke-test
