#!/bin/bash -e

if ! [ -z "$(git status --porcelain)" ]; then
  echo "git status is not clean"
  exit 1
fi

if ! command -v goreleaser &> /dev/null; then
  go install github.com/goreleaser/goreleaser@latest
fi

cd "$(dirname "$0")/.."

goreleaser build --snapshot --rm-dist $1

echo "✅ See binaries in ./dist"
