name: Publish Release Assets

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-to-cloudflare:
    name: Publish to Cloudflare

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download assets from latest release
        run: |
          mkdir assets && \
          gh release download --repo ${{ github.repository }} --pattern '*' --dir .cloudflare/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: .cloudflare
