name: Publish Release Assets

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-to-cloudfront:
    name: Publish to CloudFront

    runs-on: ubuntu-latest

    steps:
      - name: Download assets from latest release
        run: |
          mkdir assets && \
          gh release download --repo ${{ github.repository }} --pattern '*' --dir assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync assets to S3 bucket
        run: aws s3 cp assets s3://buildpulse-test-reporter --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ASSET_PUBLICATION_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ASSET_PUBLICATION_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Invalidate Cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ASSET_PUBLICATION_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ASSET_PUBLICATION_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

  publish-to-cloudflare:
    name: Publish to Cloudflare

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download assets from latest release
        run: |
          mkdir assets && \
          gh release download --repo ${{ github.repository }} --pattern '*' --dir .cloudflare/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: .cloudflare
